### ISSUE TITLE
Integrate telegram bot for content saving as module

### ISSUE THREAD

**Issue by MicrowaveDev** [galtproject/geesome-node#621]

**Comment by Vlad-majep** [comment]
create database with botId encrypted bot token and userId

**Comment by Vlad-majep** [comment]
create an endpoint for telegram webhook to receive messages from it

**Comment by Vlad-majep** [comment]
https://github.com/yagop/node-telegram-bot-api/blob/4ec6a6884000786d826c0e1be77d312267b6e1d4/examples/webhook/express.js#L18
